# Generated by Django 2.0.2 on 2018-05-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='order1',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='order2',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='order3',
        ),
        migrations.AddField(
            model_name='donor',
            name='position_x',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='position_y',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
