
# Generated by Django 2.0.2 on 2018-05-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_populate_position_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('position_x', 'position_y')},
        ),
    ]
